exports.strategies = [
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484683",
    code: "mirror-prev-col",
    name: "Mirror-8 5.rows",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    nextMove: "-",
    __v: 2431,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 5,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484684",
    code: "mirror-prev-col",
    name: "Mirror-8 5.rows (R)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 1760,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 5,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484685",
    code: "mirror-L",
    name: "Mirror L 4x2 - 5 rows",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 1765,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 5,
    nextMove: "-",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484686",
    code: "mirror-L",
    name: "Mirror L 4x2 (R) - 5 rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 2464,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 5,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484687",
    code: "square-5-rows",
    name: "Square - 5 rows (OVER)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484688",
    code: "square-5-rows",
    name: "Square - 5 rows (UNDER)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: true,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484689",
    code: "rectangle-5-rows",
    name: "Rectangle - 5 rows (OVER)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468a",
    code: "rectangle-5-rows",
    name: "Rectangle - 5 rows (UNDER)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: true,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468b",
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 3",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 3,
    nextMove: "-",
    target: "P",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468c",
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 4",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 4,
    nextMove: "-",
    target: "P",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468d",
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 5",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 5,
    nextMove: "-",
    target: "B",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468e",
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 6",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 1767,
    activated: false,
    count: 0,
    enabled: true,
    nbRows: 6,
    nextMove: "-",
    target: "P",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb48468f",
    code: "repeat-even-row-twice-on-next-col_6rows",
    name: "Repeat cell from even rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    target: "B",
    __v: 4724,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484690",
    code: "repeat-even-row-twice-on-next-col_6rows",
    name: "Repeat cell from even rows (R)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: true,
    hasWonInCol: false,
    target: "P",
    __v: 2438,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484691",
    code: "repeat-1st-bet-all_6rows",
    name: "Repeat 1st deal all down",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 4630,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    nextMove: "-",
    target: "B",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60f99d22c6f4d847eb484692",
    code: "repeat-1st+4th-bet-twice_6rows",
    name: "Repeat deal on R1 & R4 down twice",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 2438,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    nextMove: "-",
    target: "P",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "60fca026aa2ec20a3807ddcb",
    code: "bet-opp-on-nxt-3-twice",
    name: "Bet opposite on next 3 twice",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    target: "B",
    enabled: true,
    activated: false,
    __v: 2345,
    hasWonInCol: false,
    count: 0,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610716dce193ce6f547c2a2b",
    code: "mirror-L",
    name: "Mirror L 5x2 - 6 rows",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 2436,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    nextMove: "-",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "61072304e193ce6f547c2a2c",
    code: "mirror-L",
    name: "Mirror L 5x2 (R) - 6 rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 4003,
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "61072b40e193ce6f547c2a32",
    code: "mirror-prev-col",
    name: "Mirror 12 6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: false,
    hasWonInCol: false,
    __v: 2364,
    target: "P",
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "61072b66e193ce6f547c2a33",
    code: "mirror-prev-col",
    name: "Mirror 12 6rows (R)",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    reverse: true,
    hasWonInCol: false,
    __v: 4618,
    target: "P",
    enabled: true,
    activated: false,
    count: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "61085f698e400b62ae00adba",
    code: "triangle_6rows",
    name: "Triangle r1 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "B",
    targetIdx: 0,
    row: 0,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610aa3ce55096c255b1c6512",
    code: "triangle_6rows",
    name: "Triangle r2 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "P",
    targetIdx: 1,
    row: 1,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610aa3f255096c255b1c6513",
    code: "triangle_6rows",
    name: "Triangle r3 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "B",
    targetIdx: 2,
    row: 2,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610aa3f255096c255b1c6514",
    code: "triangle_6rows",
    name: "Triangle r4 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: false,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "B",
    targetIdx: 3,
    row: 3,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: ["P", "P", "B", "P"],
    targetBets: ["B", "B", "P", "B", "B", "P"],
    history: [],
    _id: "610e772c6a4928a2413dccbc",
    code: "pattern",
    name: "Pattern: Bet BBPx2, triggered by PPBP",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    __v: 283,
    enabled: true,
    activated: false,
    count: 0,
    hasWonInCol: false,
    targetIdx: 0,
    metrics: { innerPercents: [] },
    nextMove: "-",
  },
  {
    pattern: ["B", "B", "P", "B"],
    targetBets: ["P", "P", "B", "P", "P", "B"],
    history: [],
    _id: "610e842b6a4928a2413dccbd",
    code: "pattern",
    name: "Pattern: Bet PPBx2, triggered by BBPB",
    lvl: 1,
    maxLvl: 10,
    percent: 0,
    reverse: false,
    __v: 283,
    enabled: true,
    activated: false,
    count: 0,
    hasWonInCol: false,
    targetIdx: 1,
    nextMove: "-",
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610e9121e0055253b6615a78",
    code: "triangle_6rows",
    name: "Triangle (flipped) R3 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "P",
    targetIdx: 2,
    row: 2,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610e913ae0055253b6615a79",
    code: "triangle_6rows",
    name: "Triangle (flipped) R4 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "P",
    targetIdx: 3,
    row: 3,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610e914ce0055253b6615a7a",
    code: "triangle_6rows",
    name: "Triangle (flipped) R5 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "B",
    targetIdx: 4,
    row: 4,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
  {
    pattern: [],
    targetBets: [],
    history: [],
    _id: "610e9155e0055253b6615a7b",
    code: "triangle_6rows",
    name: "Triangle (flipped) R6 3x3 _6rows",
    lvl: 1,
    nextMove: "-",
    maxLvl: 10,
    percent: 0,
    hasWonInCol: false,
    reverse: true,
    __v: 3267,
    enabled: true,
    activated: false,
    count: 0,
    target: "P",
    targetIdx: 5,
    row: 5,
    nbRows: 6,
    metrics: { innerPercents: [] },
  },
];
