exports.strategies = [
  {
    code: "mirror-prev-col",
    name: "Mirror-8 5.rows",
    reverse: false,
  },
  {
    code: "mirror-prev-col",
    name: "Mirror-8 5.rows (R)",
    reverse: true,
  },
  {
    code: "mirror-L",
    name: "Mirror L 4x2 - 5 rows",
    reverse: false,
  },
  {
    code: "mirror-L",
    name: "Mirror L 4x2 (R) - 5 rows",
    reverse: true,
  },
  {
    code: "square-5-rows",
    name: "Square - 5 rows (OVER)",
    reverse: false,
  },
  {
    code: "square-5-rows",
    name: "Square - 5 rows (UNDER)",
    reverse: true,
  },
  {
    code: "rectangle-5-rows",
    name: "Rectangle - 5 rows (OVER)",
    reverse: false,
  },
  {
    code: "rectangle-5-rows",
    name: "Rectangle - 5 rows (UNDER)",
    reverse: true,
  },
  {
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 3",
    reverse: false,
    nbRows: 3,
  },
  {
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 4",
    reverse: false,
    nbRows: 4,
  },
  {
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 5",
    reverse: false,
  },
  {
    code: "copycell-to-1st-3cells-on-nextcol_6rows",
    name: "Copy cell 6",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "repeat-even-row-twice-on-next-col_6rows",
    name: "Repeat cell from even rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "repeat-even-row-twice-on-next-col_6rows",
    name: "Repeat cell from even rows (R)",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "repeat-1st-bet-all_6rows",
    name: "Repeat 1st deal all down",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "repeat-1st+4th-bet-twice_6rows",
    name: "Repeat deal on R1 & R4 down twice",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "bet-opp-on-nxt-3-twice",
    name: "Bet opposite on next 3 twice",
    reverse: false,
  },
  {
    code: "mirror-L",
    name: "Mirror L 5x2 - 6 rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "mirror-L",
    name: "Mirror L 5x2 (R) - 6 rows",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "mirror-prev-col",
    name: "Mirror 12 6rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "mirror-prev-col",
    name: "Mirror 12 6rows (R)",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle r1 3x3 _6rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle r2 3x3 _6rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle r3 3x3 _6rows",
    reverse: false,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle r4 3x3 _6rows",
    reverse: false,
    nbRows: 6,
  },
  {
    pattern: ["P", "P", "B", "P"],
    targetBets: ["B", "B", "P", "B", "B", "P"],
    code: "pattern",
    name: "Pattern: Bet BBPx2, triggered by PPBP",
  },
  {
    pattern: ["B", "B", "P", "B"],
    targetBets: ["P", "P", "B", "P", "P", "B"],
    code: "pattern",
    name: "Pattern: Bet PPBx2, triggered by BBPB",
  },
  {
    code: "triangle_6rows",
    name: "Triangle (flipped) R3 3x3 _6rows",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle (flipped) R4 3x3 _6rows",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle (flipped) R5 3x3 _6rows",
    reverse: true,
    nbRows: 6,
  },
  {
    code: "triangle_6rows",
    name: "Triangle (flipped) R6 3x3 _6rows",
    reverse: true,
    nbRows: 6,
  },
];
